# Generated by Django 3.1.7 on 2021-03-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('item_code', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_list_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_list', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=20, null=True)),
                ('isvisible', models.IntegerField(blank=True, db_column='ISVISIBLE', null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('thresholdvalue', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, db_column='QUANTITY', null=True)),
                ('price', models.FloatField(blank=True, db_column='PRICE', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, db_column='QUANTITY', null=True)),
                ('price', models.FloatField(blank=True, db_column='PRICE', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
    ]
