# Generated by Django 3.1.7 on 2021-03-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('balance', models.FloatField(db_column='BALANCE', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Variable',
                'db_table': 'Variable',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'managed': True, 'verbose_name_plural': 'Food'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': True, 'verbose_name_plural': 'inventory'},
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'managed': True, 'verbose_name_plural': 'login'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'managed': True, 'verbose_name_plural': 'purchase'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'managed': True, 'verbose_name_plural': 'sales'},
        ),
    ]
