# Generated by Django 3.1.7 on 2021-04-05 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_auto_20210403_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='complementory_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 4, 5, 20, 3, 31, 243372), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(db_column='DATE', default=datetime.datetime(2021, 4, 5, 20, 3, 31, 243372), primary_key=True, serialize=False),
        ),
    ]
